'use strict';
(() => {
type DomControl = HTMLElement & HTMLInputElement & HTMLSelectElement & HTMLTextAreaElement & HTMLDetailsElement;
const $=(id: string): DomControl => { const element=document.getElementById(id); if(!element) throw Error("Elemento não encontrado: " + id); return element as DomControl; };
let snapshot,activePath='',currentView=null,guidance=null;
const tuning=$('tuning-panel');

function showView(view){
  currentView=view;
  for(const name of ['llama','models','settings'])$(`${name}-view`).hidden=name!==view;
  $('nav-llama').classList.toggle('active',view==='llama');
  $('nav-models').classList.toggle('active',view==='models');
  $('nav-settings').classList.toggle('active',view==='settings');
  if(view==='settings'){$('tuning-settings-content').append(tuning);$('tuning-settings-content').hidden=false;$('save-settings-profile').hidden=false;$('tuning-accordion').open=true;}
  else{$('tuning-content').append(tuning);$('tuning-settings-content').hidden=true;$('save-settings-profile').hidden=false;$('tuning-accordion').open=false;}
}
type SettingKey = keyof ModelSettings;
const keys: SettingKey[]=['gpuLayers','device','context','cpuMoe','cacheK','cacheV','flash','threads','batch','ubatch'];
const caches=['f16','q8_0','q4_0','q5_0','q4_1','q5_1','f32','bf16','iq4_nl'];
for(const key of ['cacheK','cacheV'])$(key).innerHTML=caches.map(v=>`<option>${v}</option>`).join('');
function message(text,error=false){const box=currentView==='settings'?$('settings-message'):$('message');box.textContent=text;box.classList.toggle('error',error);}
async function action(fn){try{await fn();}catch(e){message(e.message||String(e),true);}}
function settings(): ModelSettings {const v: ModelSettings={gpuLayers:"",device:"",context:"",cpuMoe:"",cacheK:"",cacheV:"",flash:"",threads:"",batch:"",ubatch:""};for(const key of keys)v[key]=$(key).value.trim();return v;}
function applySettings(v){for(const key of keys)$(key).value=String(v?.[key]??'');}
function selected(){return snapshot?.models?.find(m=>m.path===$('model').value);}
function selectedSettingsModel(){return snapshot?.models?.find(m=>m.path===$('settings-model').value)||selected();}
function fillModelSelectors(models,preferred){for(const id of ['model','settings-model']){const select=$(id),previous=preferred||$('model').value;const empty=document.createElement('option');empty.value='';empty.textContent=models.length?'Selecione um modelo':'Nenhum modelo instalado';select.replaceChildren(empty,...models.map(m=>{const o=document.createElement('option');o.value=m.path;o.textContent=m.name;return o;}));if(models.some(m=>m.path===previous))select.value=previous;else select.value='';}}
function updateModelDetail(){const m=selected();if(!m){const count=snapshot?.models?.length||0;const hint=count?`Escolha um dos ${count} modelos encontrados na lista acima.`:'Nenhum GGUF encontrado. Configure uma pasta ou veja as sugestões compatíveis.';$('model-detail').textContent=hint;$('settings-model-detail').textContent=hint;activePath='';applySettings({});return;}
  const detail=`${(m.size/1024**3).toFixed(2)} GB · ${m.path}${m.projector?' · projetor multimodal':''}`;$('model-detail').textContent=detail;$('settings-model-detail').textContent=`${m.name} · ajustes salvos só para este modelo.`;activePath=m.path;const profile=snapshot.config.profiles[m.path]||{gpuLayers:'auto',device:'',context:4096,cpuMoe:'',cacheK:'f16',cacheV:'f16',flash:'auto',threads:'',batch:512,ubatch:256};applySettings(profile);}
function bytes(value){if(value==null||!Number.isFinite(Number(value)))return '—';const n=Number(value);if(n<=0)return '0 B';const units=['B','KB','MB','GB','TB'];let x=n,unit=0;while(x>=1024&&unit<units.length-1){x/=1024;unit++;}return `${x.toFixed(unit?1:0)} ${units[unit]}`;}
function renderGuidance(data){guidance=data||null;if(!data){$('guidance-summary').textContent='Não foi possível carregar as recomendações agora.';$('suggestions').replaceChildren();return;}
  const h=data.hardware||{};$('models-memory').textContent=bytes(h.memoryBytes);$('models-cpu').textContent=`${h.logicalCores||'—'} threads`;$('disk-space').textContent=bytes(data.availableDiskBytes);$('guidance-summary').textContent=data.summary||`Sugestões com base em ${h.cpu||'este hardware'} (${h.platform||''} ${h.arch||''}).`;
  const list=$('suggestions');list.replaceChildren();for(const item of data.suggestions||[]){const card=document.createElement('article');card.className='suggestion';const title=document.createElement('strong');title.textContent=item.title||'Sugestão';const detail=document.createElement('p');detail.textContent=item.detail||'';card.append(title,detail);const actions=document.createElement('div');actions.className='suggestion-actions';if(item.buttonText&&item.kind){const hfBtn=document.createElement('button');hfBtn.type='button';hfBtn.className='secondary small';hfBtn.textContent=item.buttonText;hfBtn.onclick=()=>action(()=>window.llama.openHF(item.kind));actions.append(hfBtn);}if(item.exampleUrl){const exBtn=document.createElement('button');exBtn.type='button';exBtn.className='ghost small';exBtn.textContent=`Sugestão: ${item.exampleName||'exemplo'} ↗`;exBtn.onclick=()=>action(()=>window.llama.openModelExample(item.exampleUrl));actions.append(exBtn);}if(actions.childNodes.length)card.append(actions);list.append(card);}
  $('local-count').textContent=String(snapshot?.models?.length||0);$('engine-badge').textContent=snapshot?.engineReady?'Motor pronto':'Motor pendente';
  const local=$('local-models');local.replaceChildren();if(snapshot?.models?.length){const title=document.createElement('h3');title.textContent='Modelos encontrados nestas pastas';local.append(title);for(const m of snapshot.models){const row=document.createElement('div');row.className='local-model-row';const info=document.createElement('span');info.textContent=`${m.name} · ${(m.size/1024**3).toFixed(2)} GB`;const choose=document.createElement('button');choose.className='secondary small';choose.textContent='Usar modelo';choose.onclick=()=>action(async()=>{ $('model').value=m.path;$('settings-model').value=m.path;updateModelDetail();await window.llama.selectModel(m.path);showView('llama');});row.append(info,choose);local.append(row);}}
  if(h.gpuName){const gpu=document.createElement('div');gpu.className='hardware-note';gpu.textContent=`GPU detectada: ${h.gpuName}${h.gpuMemoryBytes?` · ${bytes(h.gpuMemoryBytes)} VRAM`:''}`;list.prepend(gpu);}
  if(data.caution){const caution=document.createElement('p');caution.className='guidance-caution';caution.textContent=data.caution;list.append(caution);}
  $('analyze-model').disabled=!snapshot?.engineReady||!snapshot?.models?.length;$('copy-guidance-prompt').disabled=!data.prompt;
}
async function loadGuidance(){if(typeof window.llama.modelGuidance!=='function')return;try{renderGuidance(await window.llama.modelGuidance());}catch(e){$('guidance-summary').textContent=`Falha ao ler o hardware: ${e.message||e}`;}}
function updateNetwork(){$('network-controls').hidden=$('access-host').value==='127.0.0.1';$('key-value').hidden=true;$('key-value').textContent='';}
function updateBackendHint(){const id=$('engine-backend').value;$('engine-backend-hint').textContent=id.startsWith('cuda-')?'Para placas NVIDIA. O download inclui as bibliotecas CUDA; é necessário um driver NVIDIA compatível.':id.startsWith('rocm-')?'Para placas AMD compatíveis com ROCm; requer driver e runtime compatíveis.':id.startsWith('sycl')?'Para GPUs Intel compatíveis com SYCL; pode exigir runtime Intel.':id==='cpu'?'Executa sem aceleração de GPU.':id==='metal'?'Aceleração Apple Metal.':'Aceleração Vulkan; requer driver compatível.';}
function fillBackends(s){const select=$('engine-backend'),previous=select.value,options=s.backendOptions||[];select.replaceChildren(...options.map(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.label;return option;}));const desired=options.find(item=>item.id===previous)||options.find(item=>item.id===s.config.engineBackend)||options[0];select.value=desired?.id||'';select.disabled=s.running||s.chatRunning||!options.length;updateBackendHint();}
function showConnection(result){$('connection').hidden=!result;$('firewall-controls').hidden=snapshot?.platform!=='win32'||!result||result.scope==='Local';if(result){$('endpoint').textContent=`API: ${result.endpoint} · Interface: ${result.remoteUrl}`;if(result.scope!=='Local')$('firewall-range').value=result.scope==='Tailscale'?'100.64.0.0/10':result.host.split('.').slice(0,3).join('.')+'.0/24';}}
async function refresh(preferred?: string){snapshot=await window.llama.state();const s=snapshot;const old=preferred||s.config.selectedModelPath||$('model').value;
  if(currentView===null)showView((!s.engineReady||!s.models.length||!s.config.selectedModelPath)?'settings':'llama');
  $('memory').textContent=bytes(s.hardware.memoryBytes);$('cpu').textContent=`${s.hardware.logicalCores} threads`;$('models-memory').textContent=bytes(s.hardware.memoryBytes);$('models-cpu').textContent=`${s.hardware.logicalCores} threads`;$('local-count').textContent=String(s.models.length);
  $('platform').textContent=({win32:'Windows',linux:'Linux',darwin:'macOS'})[s.platform]||s.platform;$('engine-status').textContent=s.engineReady?'Pronto':'Pendente';$('settings-engine-status').textContent=s.engineReady?'Motor pronto':'Motor pendente';$('engine-badge').textContent=s.engineReady?'Motor pronto':'Motor pendente';$('settings-engine-badge').textContent=s.engineReady?'Pronto':'Pendente';$('engine-path').textContent=s.config.engineDir||'Nenhuma pasta selecionada';fillBackends(s);$('folder-0').textContent=s.config.modelDirs[0]||'Não configurado';$('folder-1').textContent=s.config.modelDirs[1]||'Não configurado';
  fillModelSelectors(s.models,old);$('setup-hint').hidden=s.engineReady&&s.models.length>0;updateModelDetail();
  $('launch').disabled=!s.engineReady||!s.models.length||s.running||s.chatRunning;$('stop').hidden=!s.running;$('start-chat').disabled=!s.engineReady||!s.models.length||s.running||s.chatRunning;$('open-cli-terminal').disabled=!s.engineReady||!s.models.length||s.running||s.chatRunning;$('save-settings-profile').disabled=!s.models.length;$('stop-chat').hidden=!s.chatRunning;$('send-chat').disabled=!s.chatRunning;
  $('access-host').replaceChildren(...s.accessOptions.map(item=>{const o=document.createElement('option');o.value=item.host;o.textContent=item.name;return o;}));$('access-host').value=s.accessOptions.some(x=>x.host===s.config.accessHost)?s.config.accessHost:'127.0.0.1';$('parallel').value=s.config.parallel||1;$('access-host').disabled=s.running;$('parallel').disabled=s.running;$('rotate-key').disabled=s.running;updateNetwork();showConnection(s.active);
  await loadGuidance();
}

$('nav-llama').onclick=()=>showView('llama');$('nav-models').onclick=()=>showView('models');$('nav-settings').onclick=()=>showView('settings');$('open-settings').onclick=()=>showView('settings');$('open-models').onclick=()=>showView('models');
$('finish-setup').onclick=()=>action(async()=>{await window.llama.completeSetup();await refresh();showView('llama');});
$('model').addEventListener('change',()=>{const path=$('model').value;$('settings-model').value=path;updateModelDetail();if(path)action(()=>window.llama.selectModel(path));});$('settings-model').addEventListener('change',()=>{const path=$('settings-model').value;$('model').value=path;updateModelDetail();if(path)action(()=>window.llama.selectModel(path));});
$('refresh').onclick=()=>action(()=>refresh());$('refresh-settings-models').onclick=()=>action(()=>refresh());$('refresh-guidance').onclick=()=>action(async()=>{guidance=null;await loadGuidance();});
document.querySelectorAll<HTMLElement>('[data-folder]').forEach(b=>b.onclick=()=>action(async()=>{await window.llama.chooseDir('models',Number(b.dataset.folder));await refresh();}));
document.querySelectorAll<HTMLElement>('[data-clear-folder]').forEach(b=>b.onclick=()=>action(async()=>{await window.llama.clearDir(Number(b.dataset.clearFolder));await refresh();}));
document.querySelectorAll<HTMLElement>('[data-open-folder]').forEach(b=>b.onclick=()=>action(()=>window.llama.openModelDir(Number(b.dataset.openFolder))));
$('select-engine').onclick=()=>action(async()=>{await window.llama.chooseDir('engine');await refresh();});
$('import-profiles').onclick=()=>action(async()=>{const result=await window.llama.importLegacyProfiles();if(!result)return;await refresh();message(`Perfis importados: ${result.imported}. Sem modelo no local configurado: ${result.missing}. Já existentes: ${result.existing}. Linhas inválidas: ${result.invalid}.`);});
$('engine-backend').onchange=updateBackendHint;
$('install-engine').onclick=()=>action(async()=>{message('Buscando release oficial do llama.cpp…');$('install-engine').disabled=true;$('engine-backend').disabled=true;$('download-progress').hidden=false;try{await window.llama.installEngine($('engine-backend').value);message('Motor instalado.');await refresh();}finally{$('install-engine').disabled=false;$('engine-backend').disabled=false;$('download-progress').hidden=true;}});
$('hf-moe').onclick=()=>action(()=>window.llama.openHF('moe'));$('hf-dense').onclick=()=>action(()=>window.llama.openHF('dense'));$('hf-full').onclick=()=>action(()=>window.llama.openHF('full'));const hfQuantized=$('hf-quantized');if(hfQuantized)hfQuantized.onclick=()=>action(()=>window.llama.openHF('quantized'));const hfAll=$('hf-all');if(hfAll)hfAll.onclick=()=>action(()=>window.llama.openHF('all'));
$('manual-pt').onclick=()=>action(()=>window.llama.openManual('pt-BR'));$('manual-en').onclick=()=>action(()=>window.llama.openManual('en'));
$('recommend').onclick=()=>action(async()=>{const m=selectedSettingsModel();if(!m)throw Error('Instale ou selecione um modelo GGUF para calcular os ajustes.');applySettings(await window.llama.recommend(m.path));$('tuning-message').textContent='Sugestão aplicada aos campos. Confira os valores e salve o perfil deste modelo.';});
$('tune').onclick=()=>action(async()=>{const m=selectedSettingsModel();if(!m)throw Error('Instale ou selecione um modelo GGUF.');$('tune').disabled=true;$('tuning-message').textContent='Comparando microbatch com llama-bench. Isso pode levar alguns minutos.';try{const result=await window.llama.tune(m.path,settings());applySettings(result.settings);const best=result.results.find(r=>r.ubatch===result.settings.ubatch);$('tuning-message').textContent=`Microbatch ${best.ubatch} escolhido: geração ${best.generationTps.toFixed(1)} tokens/s. Confira e salve o perfil.`;}finally{$('tune').disabled=false;}});
$('save-settings-profile').onclick=()=>action(async()=>{const m=selectedSettingsModel();if(!m)throw Error('Instale ou selecione um modelo GGUF para salvar os ajustes.');await window.llama.saveProfile(m.path,settings());$('settings-message').textContent='Ajustes salvos para este modelo.';$('message').textContent='Ajustes salvos para este modelo.';});
$('access-host').onchange=updateNetwork;
$('show-key').onclick=()=>action(async()=>{if(!$('key-value').hidden){$('key-value').hidden=true;$('key-value').textContent='';return;}$('key-value').textContent=await window.llama.getKey();$('key-value').hidden=false;});
$('copy-key').onclick=()=>action(async()=>{await window.llama.copyKey();message('Chave copiada. Evite colá-la em locais públicos.');});$('rotate-key').onclick=()=>action(async()=>{$('key-value').textContent=await window.llama.rotateKey();$('key-value').hidden=false;message('Nova chave criada. A anterior deixou de funcionar.');});
$('copy-endpoint').onclick=()=>action(async()=>{await window.llama.copyEndpoint();message('Link da API copiado.');});$('copy-browser-link').onclick=()=>action(async()=>{await window.llama.copyBrowserLink();message('Link da interface copiado. Envie também a chave de API por um canal seguro.');});
$('create-firewall').onclick=()=>action(async()=>{$('create-firewall').disabled=true;try{await window.llama.createFirewallRule($('firewall-range').value.trim());message('Regra de firewall criada para a porta ativa e a faixa informada.');}finally{$('create-firewall').disabled=false;}});
$('launch').onclick=()=>action(async()=>{const m=selected();if(!m)throw Error('Escolha um modelo.');$('launch').disabled=true;message('Carregando modelo…');$('log').textContent=`[launcher] Carregando modelo ${m.name} no servidor...\n`;try{const result=await window.llama.launch(m.path,settings(),{host:$('access-host').value,parallel:Number($('parallel').value)});snapshot.active=result;showConnection(result);message(`Interface aberta: ${result.browserUrl}`);$('stop').hidden=false;$('access-host').disabled=true;$('parallel').disabled=true;$('rotate-key').disabled=true;}catch(e){$('launch').disabled=false;throw e;}});
$('stop').onclick=()=>action(async()=>{await window.llama.stop();message('Encerrando servidor…');});
$('start-chat').onclick=()=>action(async()=>{const m=selected();if(!m)throw Error('Escolha um modelo.');$('chat-output').textContent='Carregando modelo…\n';$('start-chat').disabled=true;$('stop-chat').hidden=false;$('send-chat').disabled=false;$('launch').disabled=true;try{await window.llama.startChat(m.path,settings());}catch(e){$('start-chat').disabled=false;$('stop-chat').hidden=true;$('send-chat').disabled=true;$('launch').disabled=false;throw e;}});
$('open-cli-terminal').onclick=()=>action(async()=>{const m=selected();if(!m)throw Error('Escolha um modelo.');await window.llama.openCliTerminal(m.path,settings());message('CLI aberto em um terminal separado. Encerre-o nessa janela quando terminar.');});
$('send-chat').onclick=()=>action(async()=>{const value=$('chat-input').value;if(!value.trim())return;await window.llama.sendChat(value);$('chat-input').value='';});$('chat-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('send-chat').click();}});$('stop-chat').onclick=()=>action(async()=>{await window.llama.stopChat();$('stop-chat').disabled=true;});
$('copy-guidance-prompt').onclick=()=>action(async()=>{const prompt=await window.llama.copyGuidancePrompt();$('prompt-text').textContent=prompt||guidance?.prompt||'';$('prompt-text').hidden=!$('prompt-text').textContent; $('guidance-message').textContent='Prompt copiado. Você pode colá-lo em qualquer conversa com um modelo.';});
$('analyze-model').onclick=()=>action(async()=>{const m=selected()||snapshot?.models?.[0];if(!m)throw Error('Instale um modelo GGUF antes de pedir a análise.');$('model').value=m.path;$('settings-model').value=m.path;updateModelDetail();await window.llama.selectModel(m.path);showView('llama');$('chat-output').textContent='Análise de hardware e ajustes sugeridos. Revise a resposta antes de alterar configurações.\n\n';$('start-chat').disabled=true;$('stop-chat').hidden=false;$('send-chat').disabled=true;$('launch').disabled=true;try{await window.llama.analyzeWithModel(m.path,settings());}catch(e){$('start-chat').disabled=false;$('stop-chat').hidden=true;$('send-chat').disabled=true;$('launch').disabled=false;throw e;}});
window.llama.onProgress(p=>{$('progress-bar').style.width=`${Math.min(100,p.percent)}%`;$('progress-text').textContent=`${p.label}: ${p.percent}%`;});window.llama.onTuneProgress(text=>{$('tuning-message').textContent=text;});
window.llama.onLog(line=>{const box=$('log');const current=box.textContent.startsWith('Nenhum registro ainda')?'':box.textContent;box.textContent=(current+line).slice(-30000);box.scrollTop=box.scrollHeight;});
window.llama.onStopped(code=>{message(`Servidor encerrado (${code??'sem código'}).`);snapshot.active=null;showConnection(null);$('stop').hidden=true;$('launch').disabled=false;$('access-host').disabled=false;$('parallel').disabled=false;$('rotate-key').disabled=false;});
window.llama.onChatOutput(data=>{const box=$('chat-output');box.textContent=(box.textContent+data.text).slice(-100000);box.scrollTop=box.scrollHeight;});
window.llama.onChatStopped(result=>{$('chat-output').textContent+=`\n[Conversa encerrada: ${result.code??result.signal??'sem código'}]\n`;$('stop-chat').hidden=true;$('stop-chat').disabled=false;$('send-chat').disabled=true;$('start-chat').disabled=false;$('launch').disabled=false;});
refresh().catch(e=>message(e.message,true));
})();
